name: Check assets ownership

permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  check-signature:
    runs-on: ubuntu-latest
    steps:
      - uses: multiversx/mx-assets-checker@add-existing-ticker-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADMIN_ADDRESS: ${{ secrets.ADMIN_ADDRESS }}
